

CREATE TABLE ROWERS(
ROWER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
FIRSTNAME TEXT NOT NULL,
LASTNAME TEXT NOT NULL
);


CREATE TABLE ROWING_RESULTS(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
BOAT TEXT NOT NULL,
PLACE INT NOT NULL,
TIME INT NOT NULL,
ROWER_ID NOT NULL,
FOREIGN KEY (ROWER_ID)
    references ROWERS (ROWER_ID)
);


